# Generated by Django 4.2.3 on 2023-08-09 09:09

from django.db import migrations
import task_manager.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_siteuser_first_name_alter_siteuser_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='siteuser',
            managers=[
                ('objects', task_manager.users.models.SiteUserManage()),
            ],
        ),
    ]
